config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :todos
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :listItem, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo
    else
      render 'new'
    end
  end

  private
  def todo_params
    params.require(:todo).permit(:listitem, :text)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>Todo List</h1>


<%= link_to 'New Todo', new_todo_path %>

<table>
  <tr>
    <th>List Item</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @todos.each do |todo| %>
    <tr>
      <td><%= todo.listitem %></td>
      <td><%= todo.text %></td>
      <td><%= link_to 'Show', todo_path(todo) %></td>
    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<h1>New Todo</h1>


<%= form_with scope: :todo, url: todos_path, local: true do |form| %>
  <p>
    <%= form.label :list_item %><br>
    <%= form.text_field :listitem %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p>
  <strong>List Item:</strong>
  <%= @todo.listitem %>
</p>

<p>
  <strong>Text:</strong>
  <%= @todo.text %>
</p>

<%= link_to 'Back', todos_path %>

app/views/welcome/index.html.erb
<h1>Darn Todos</h1>
<%= link_to 'My Todo List', controller: 'todos' %>